# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-25 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190825_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_author',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
